spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/DB_COMMENT_HUB
    username: postgres
    password: postgres
  application:
    name: CommentHub
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
commenthub:
  security:
    secret: QFxH]$9S7h/#LVtOm'sY[%C2{r/Iv&Cys(+ETH~lN[bX6>T}+N_BF%[iyA+f=7i